### ISSUE TITLE
Backport Instructions

### ISSUE THREAD

**Issue by DougHall** [blegay/jwt_component#1]
I would really love to use this plugin with 4D v17. You say that the plugin can be backported to v14, but there are no instructions or links on how to do this. I'd appreciate some direction!

**Comment by blegay** [comment]
Hi,

Just have top copy and paste the method to a v17 structure.

I have component which allows me to drag and drop a liste of 4dm files in a v17 structure 

Here you go :

[jwt_component.4dbase.zip](https://github.com/blegay/jwt_component/files/6136997/jwt_component.4dbase.zip)
